[package]
name = "dapu"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.24"
crossterm = "0.27"
ron = "0.8"
dirs = "5"
serde = { version="1", features=["derive"] }
clap = { version = "4.4", features = ["derive"] }
